apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app-container
          image: yourdockerhubusername/your-app:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: app-storage
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: your-app-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: your-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
